// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYnieA0cl0DWANoNt0bcTatwyGvTEr0Ww',
    appId: '1:236670279140:web:90d21d80498afbb7517bf1',
    messagingSenderId: '236670279140',
    projectId: 'zanna-clothing',
    authDomain: 'zanna-clothing.firebaseapp.com',
    storageBucket: 'zanna-clothing.appspot.com',
    measurementId: 'G-PLNT5KF4V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA2k23okgjXqNtmt-pOq3OfhXd3YyPFMM',
    appId: '1:236670279140:android:813d20cd943478bb517bf1',
    messagingSenderId: '236670279140',
    projectId: 'zanna-clothing',
    storageBucket: 'zanna-clothing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL_NC6HP_tdv6TV2Xljny6UlcZyMMeDbs',
    appId: '1:236670279140:ios:1b3f11bf8b5a5a44517bf1',
    messagingSenderId: '236670279140',
    projectId: 'zanna-clothing',
    storageBucket: 'zanna-clothing.appspot.com',
    iosClientId: '236670279140-d4aqmc2snb9ul0f54o9deuqhcoji2kkq.apps.googleusercontent.com',
    iosBundleId: 'com.spielereinzig.zannasclothing.zannasClothing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL_NC6HP_tdv6TV2Xljny6UlcZyMMeDbs',
    appId: '1:236670279140:ios:36a398f438ae5c07517bf1',
    messagingSenderId: '236670279140',
    projectId: 'zanna-clothing',
    storageBucket: 'zanna-clothing.appspot.com',
    iosClientId: '236670279140-umfvagaa39mjkt14822tqhgf1ovrpa1i.apps.googleusercontent.com',
    iosBundleId: 'com.spielereinzig.zannasclothing.zannasClothing.RunnerTests',
  );
}
